services:
  - type: web
    name: vakeel-ai
    env: python
    plan: free           # change to starter/standard for production
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=4 --threads=2 --timeout=120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
